import { Providers } from "@/components/providers";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { MainNav } from "@/components/layouts/MainNav";
import SessionPRO from "@/components/SessionPRO";
const inter = Inter({ subsets: ["latin"] });
import Script from 'next/script'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Script defer src="http://sowwk88co0wsgg8c4480ggok.37.60.235.169.sslip.io/script.js" data-website-id="e1650544-cb11-4728-acb6-dd3c7821ceb0"/>
      <body className={inter.className}>
        <SessionPRO>
          <Providers>{children}</Providers>
        </SessionPRO>
      </body>
    </html>
  );
}
